name: landing_page_boilerplate
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0
  flutter_svg: ^1.0.3
  auto_size_text: ^3.0.0
  url_launcher: ^6.0.20
  go_router: ^6.0.3
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.7
  flutter_launcher_icons: ^0.11.0

flutter_native_splash:
  color: "#222527"

flutter_icons:
 web:
  generate: true
  image_path: "assets/app/fav_icon.png"

flutter:

  uses-material-design: true

  assets:
    - 'assets/images/'
    - 'assets/icons/'

  fonts:
    - family: Sk-Modernist
      fonts:
        - asset: assets/fonts/sk_modernist/Sk-Modernist-Bold.ttf
        - asset: assets/fonts/sk_modernist/Sk-Modernist-Light.ttf
        - asset: assets/fonts/sk_modernist/Sk-Modernist-Regular.ttf